function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Apr-2019 11:29:57

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,...
    'Color',[0 0 0]);
set(plot1(1),'LineWidth',1);
text(2003.8,0.70,'Gratz, Grutter rulings');
text(2006.0,0.90,{'HFAI fully \rightarrow','implemented'});
text(2009.3,1.00,{'Early Action','abolished'});
text(2009.7,0.80,{'0%-10%','program','rolled out'});
text(2013.3,1.10,{'Early Action','reinstated'});
%line([2008.5 2008.5],get(axes1,'YLim'),'Color',[0 0 0]);
%line([2011.5 2011.5],get(axes1,'YLim'),'Color',[0 0 0]);
%line([2015.5 2015.5],get(axes1,'YLim'),'Color',[0 0 0]);
line([2007.5 2007.5],[-0.2 1.2],'Color',[0 0 0]);
line([2008.5 2008.5],[-0.2 1.2],'Color',[0 0 0]);
line([2011.5 2011.5],[-0.2 1.2],'Color',[0 0 0]);
line([2015.5 2015.5],[-0.2 1.2],'Color',[0 0 0]);

% Create ylabel
ylabel('Growth in Total Applications Since Class of 2000');

% Create xlabel
xlabel('Harvard Class');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[2000 2017]);
box(axes1,'on');
% Create legend
%legend1 = legend(axes1,'show');
%set(legend1,...
%    'Position',[0.686607142857142 0.852380952380953 0.2125 0.0630952380952381]);

% Save as pdf fit to image size
set(gcf,'Units','inches');
screenposition = get(gcf,'Position');
set(gcf,...
    'PaperPosition',[0 0 screenposition(3:4)],...
    'PaperSize',[screenposition(3:4)]);
saveas(gcf,'../FiguresAndTables/applicationsAgg','eps');
    print -dpdf -painters ../FiguresAndTables/applicationsAgg
%The first two lines measure the size of your figure (in inches). The next line configures the print paper size to fit the figure size. The last line uses the print command and exports a vector pdf document as the output.


